### ISSUE TITLE
Find out which operators to adapt

### ISSUE THREAD

**Issue by NHoff95** [NHoff95/hyrise#10]

**Comment by jchromik** [comment]
Problematic functions are:
```c++
void create_new_chunk();
void emplace_chunk(Chunk chunk);
Chunk& get_modifiable_chunk(ChunkID chunk_id, PartitionID partition_id=PartitionID{0});
const Chunk& get_chunk(ChunkID chunk_id, PartitionID partition_id=PartitionID{0}) const;
ProxyChunk get_modifiable_chunk_with_access_counting(ChunkID chunk_id, PartitionID partition_id=PartitionID{0});
const ProxyChunk get_chunk_with_access_counting(ChunkID chunk_id, PartitionID partition_id=PartitionID{0}) const;
```

We have to find all calls to these functions and make them partition aware.

The interfaces of:
```c++
void create_new_chunk();
void emplace_chunk(Chunk chunk);
```
will have to be changed to take a `PartitionID` as argument as well.

**Comment by franticBIT** [comment]
The function `get_modifiable_chunk_with_access_counting` is not used at all.

As already mentioned by Stefan, we definitley must adapt:
- insert
- delete
- export_*
- import_*
- print

And since we don't have unique chunk ids, which might make this less invasive, we actually have to take a look at almost all of them:
- abstract_operator
- aggregate
- difference
- index_scan
- join_*
- limit
- product
- projection
- sort
- table_scan
- union_*
- update
- validate

What was the result of the discussion regarding the preservation of the partitioning during the query (after get_table). If we strip the partitioning with an optimizer, it might also make things easier.
