### ISSUE TITLE
Table load & persist to disk

### ISSUE THREAD

**Issue by NHoff95** [NHoff95/hyrise#19]
As Stefan already mentioned, we have to check if the process of persisting to and loading from disk has to be adapted for partitioning.
Depending on the concrete process, we may store the table partitioned (we have to adapt the format of how the table is persisted on disk) or as it is currently (and have to partition on every load process).

**Comment by NHoff95** [comment]
Writing the tables unpartitioned is a valid solution (Stefan)

**Comment by NHoff95** [comment]
First task: Write test case to check if import/export currently still works with partitioning

**Comment by franticBIT** [comment]
@NHoff95 @jchromik Both csv and binary export are working for partitioned tables. I added a simple test case for each. Should we leave it at that or should I find a solution to keep the partitioning?

**Comment by jchromik** [comment]
IMHO, if there is an easy way of doing this, we can try to keep partitioning when serializing. Otherwise we can leave it like that.
I suppose investing an hour (or something like that) on a spike. If you do not find a good and easy solution stop and better work on another issue.

What do you think of this @franticBIT @NHoff95?

**Comment by franticBIT** [comment]
Well, I already had a look for the CSV export. I wouldn't describe the implementation as easy or trivial...

**Comment by franticBIT** [comment]
Adaption postponed, see #35
